name: Test PyFrm install

on:
  workflow_dispatch:

env:
  DOCKER_TEST_FILES_PATH: "./build_tools/docker/test/"
  TEST_FILES_EXT: ".Dockerfile"

jobs:
  on_linux_x86_64:
    strategy:
      fail-fast: true
      matrix:
        image: [ "debian10" ]
    runs-on: ubuntu-latest
    name: 🐍 • ${{ matrix.image }} • x86_64
    env:
      dockerfile: ${{ format('{0}{1}{2}', env.DOCKER_TEST_FILES_PATH, env.matrix.image, env.TEST_FILES_EXT) }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          install: true
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          file: dockerfile
          tags: blablabla

      - name: Test
        run: docker run --rm blablabla

#      - name: Run tests2
#        run: docker run -it self_install_test

#  on_linux_aarch64:
#    strategy:
#      fail-fast: true
#      matrix:
#        image: [ "debian10" ]
#    runs-on: ubuntu-latest
#    name: 🐍 • ${{ matrix.image }} • aarch64
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#        with:
#          platforms: arm64
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#        with:
#          buildkitd-flags: --debug
#          install: true
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Run tests
#        run: docker build --file ${{ env.docker_file }} --platform arm64 -t self_install_test .
#        env:
#          docker_file: ${{ env.DOCKER_TEST_FILES_PATH }}${{ matrix.image }}${{ env.TEST_FILES_EXT }}
#
#      - name: Run tests2
#        run: docker run -it self_install_test

# , "debian:bullseye", "ubuntu:21.10", "ubuntu:latest", "alpine:latest", "fedora:latest"
# wih pip
# without pip
#  on_alpine:
#    strategy:
#      fail-fast: true
#      matrix:
#        python: [ "3.8" , "3.9" , "3.10" , "standalone" ]
#        arch: [ x86_64 , aarch64 ]
#    runs-on: ubuntu-latest
#    name: 🐍 • Alpine • ${{ matrix.python }} • ${{ matrix.arch }}
#
#    steps:
#      - uses: actions/checkout@v2
#
#  on_macos:
#    strategy:
#      fail-fast: true
#      matrix:
#        python: [ "3.9" , "3.10" , "standalone"]
#    runs-on: macos-latest
#    name: 🐍 • macOS • ${{ matrix.python }}  • x86_64
#
#    steps:
#      - uses: actions/checkout@v2
