name: Test PyFrm install

on:
  workflow_dispatch:

env:
  DOCKER_TEST_FILES_PATH: "./build_tools/docker/test/"
  TEST_FILES_EXT: ".Dockerfile"

jobs:
  on_linux:
    strategy:
      fail-fast: true
      matrix:
        image: [ "debian10" ]
        arch: [ "x86_64", "aarch64" ]
    runs-on: ubuntu-latest
    name: 🐍 • ${{ matrix.image }} • ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
          install: true

      - name: Build image
        run: |
          echo ${{ env.DOCKER_TEST_FILES_PATH }}${{ matrix.image }}${{ env.TEST_FILES_EXT }}
          docker build --file ${{ env.DOCKER_TEST_FILES_PATH }}${{ matrix.image }}${{ env.TEST_FILES_EXT }} .



#      - name: Set up QEMU
#        if: matrix.arch == 'aarch64'
#        uses: docker/setup-qemu-action@v1
#        with:
#          platforms: arm64
# , "debian:bullseye", "ubuntu:21.10", "ubuntu:latest", "alpine:latest", "fedora:latest"
# wih pip
# without pip
#  on_alpine:
#    strategy:
#      fail-fast: true
#      matrix:
#        python: [ "3.8" , "3.9" , "3.10" , "standalone" ]
#        arch: [ x86_64 , aarch64 ]
#    runs-on: ubuntu-latest
#    name: 🐍 • Alpine • ${{ matrix.python }} • ${{ matrix.arch }}
#
#    steps:
#      - uses: actions/checkout@v2
#
#  on_macos:
#    strategy:
#      fail-fast: true
#      matrix:
#        python: [ "3.9" , "3.10" , "standalone"]
#    runs-on: macos-latest
#    name: 🐍 • macOS • ${{ matrix.python }}  • x86_64
#
#    steps:
#      - uses: actions/checkout@v2
