name: Test PyFrm install

on:
  workflow_dispatch:

jobs:
  on_linux:
    strategy:
      fail-fast: true
      matrix:
        python: [ "3.7" , "3.8" , "3.9" , "3.10" , "standalone"]
        arch: [ x86_64 , aarch64 ]
        exclude:
          - python: "3.7"
            arch: aarch64
    runs-on: ubuntu-latest
    name: 🐍 • Linux • ${{ matrix.python }} • ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

  on_alpine:
    strategy:
      fail-fast: true
      matrix:
        python: [ "3.8" , "3.9" , "3.10" , "standalone" ]
        arch: [ x86_64 , aarch64 ]
    runs-on: ubuntu-latest
    name: 🐍 • Alpine • ${{ matrix.python }} • ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v2

  on_macos:
    strategy:
      fail-fast: true
      matrix:
        python: [ "3.9" , "3.10" , "standalone"]
    runs-on: macos-latest
    name: 🐍 • macOS • ${{ matrix.python }}  • x86_64

    steps:
      - uses: actions/checkout@v2
